# config/packages/ai.yaml
ai:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'

    agent:
        default:
            platform: 'ai.platform.openai'
            model: 'gpt-5-mini'
            tools: ['App\Helper\AiTools']
            prompt:
                text: |
                    Tu es un assistant et tu peux utiliser des outils PHP pour r√©pondre aux
                    questions lorsque c'est pertinent.
