parameters:
    mailer_sender: '%env(MAILER_SENDER)%'
    shufler_video:
        max_list: 11
        max_list_couch: 99
        index_max_anim: 5
        index_max_music: 12
        index_max_autre: 4
        api_max_list: 25
        intro_couch: '67lnjV6SrFw'
        no_signal: '/images/no_signal.png'

        categories:
            1: Anim
            2: Music Moment
            3: Strange
            4: Funny
            6: Seen on Tv
            8: Movie Time
            9: Nature

        genres:
            -1: Autre
            1: Jazz/Blues
            2: Rock n'Roll
            3: Rock/Pop
            4: Soul/Funk
            5: Reggae/Ragga/Dub
            6: Chanson
            7: Punk/Alternatif
            8: Hard-Rock
            9: Blues Rock
            10: Electro/DJs
            11: World
            12: Roots/Folk Rock
            13: Rock progressif/psyché',
            14: Variétés/Pop
            15: Trip-Hop
            16: Afrobeat

        periods:
            - 2016-2030
            - 2001-2015
            - 1986-2000
            - 1971-1985
            - 1956-1970
            - 1940-1955
            - <1939

        priorities:
            - 1
            - 2
            - 3
            - 4

    shufler_flux:
        max_flux_card: 6

    youtube_api_url: 'https://www.googleapis.com/youtube/v3'
    youtube_key: '%env(YOUTUBE_KEY)%'
    vimeo_api_url: 'https://vimeo.com/api/v2'
    vimeo_secret: '%env(VIMEO_SECRET)%'
    vimeo_id: '%env(VIMEO_ID)%'
    vimeo_access_token: '%env(VIMEO_ACCESS_TOKEN)%'

    music_collection:
        batch_size: 20
        csv_path: '%uploads%csv/music.csv'
        last_fm_key: '%env(LAST_FM_KEY)%'
        last_fm_secret: '%env(LAST_FM_SECRET)%'
        last_fm_api_url: 'https://ws.audioscrobbler.com/2.0'
        no_cover_path: '/images/no_cover.jpeg'
        music_all_nb_b_page: 250
        max_nb_albums: 60
        max_nb_artists: 500
        max_random: 100
        track_fields:
            - data: youtubeKey
              orderable: false
            - data: auteur
              orderable: true
            - data: titre
              orderable: true
            - data: numero
              orderable: true
            - data: album
              orderable: true
            - data: annee
              orderable: true
            - data: artiste
              orderable: true
            - data: genre
              orderable: true
            - data: duree
              orderable: true
            - data: pays
              orderable: true
            - data: bitrate
              orderable: true
            - data: note
              orderable: true
        album_fields:
            - data: youtubeKey
              orderable: false
            - data: album
              orderable: true
            - data: artiste
              orderable: true
            - data: annee
              orderable: false
            - data: genre
              orderable: false
        cloud-track_fields:
            - data: youtubeKey
              orderable: false
            - data: auteur
              orderable: true
            - data: titre
              orderable: true
            - data: annee
              orderable: true
            - data: genre
              orderable: true
            - data: pays
              orderable: true
            - data: note
              orderable: true
        cloud-album_fields:
            - data: youtubeKey
              orderable: false
            - data: name
              orderable: true
            - data: auteur
              orderable: true
            - data: annee
              orderable: true
            - data: genre
              orderable: true
    sniffer:
        upload_directory: 'sniffer'

    resources:
        downloads: 'resources'
        fixtures_filepath: 'datas/fixtures.json'
